In [1]:
%pip install pandas numpy matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\jaime.martinez\appdata\roaming\python\python310\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\jaime.martinez\appdata\roaming\python\python310\site-packages (2.2.6)
Requirement already satisfied: matplotlib in c:\users\jaime.martinez\appdata\roaming\python\python310\site-packages (3.10.8)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jaime.martinez\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jaime.martinez\appdata\roaming\python\python310\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jaime.martinez\appdata\roaming\python\python310\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\jaime.martinez\appdata\roaming\python\python310\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\jaime.martinez\appdata\roaming\python\python310\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\jaime.martinez\appdata\roaming\python\python310\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\jaime.martinez\appdata\roaming\python\python310\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\jaime.martinez\appdata\roaming\python\python310\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\jaime.martinez\appdata\roaming\python\python310\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\jaime.martinez\appdata\roaming\python\python310\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\jaime.martinez\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.options.display.float_format = '{:.2f}'.format

In [3]:
df = pd.read_csv('repsol_2500.csv', decimal=',')
display(df.head()) # para mostrar las primeras 5 filas del dataframe
df.dtypes

                  Date  Open  High   Low  Close    Volume
0  14/05/2019 17:36:00 14.21 14.45 14.17  14.42  15796073
1  15/05/2019 17:36:00 14.46 14.53 14.34  14.50   6795939
2  16/05/2019 17:36:00 14.47 14.70 14.42  14.69   7378905
3  17/05/2019 17:36:00 14.69 14.83 14.58  14.79   7442691
4  20/05/2019 17:36:00 14.81 15.04 14.81  14.88   7758119

Date       object
Open      float64
High      float64
Low       float64
Close     float64
Volume      int64
dtype: object

### 2. Inspección de datos

- Muestra las 4 primeras filas y las 3 últimas filas del dataframe para familiarizarte con la estructura de los datos.
- Muestra el número de filas y columnas del dataframe.
- Muestra el tipo de datos de cada columna.

In [ ]:
df.head(4)

                  Date  Open  High   Low  Close    Volume
0  14/05/2019 17:36:00 14.21 14.45 14.17  14.42  15796073
1  15/05/2019 17:36:00 14.46 14.53 14.34  14.50   6795939
2  16/05/2019 17:36:00 14.47 14.70 14.42  14.69   7378905
3  17/05/2019 17:36:00 14.69 14.83 14.58  14.79   7442691

In [ ]:
display(df.tail(3))

                     Date  Open  High   Low  Close    Volume
1746  13/03/2026 17:36:00 22.39 23.00 22.35  23.00  10027236
1747  16/03/2026 17:36:00 23.16 24.30 23.01  23.32   8822412
1748  17/03/2026 17:36:00 23.50 24.23 23.40  24.19   7910437

In [ ]:
df.shape

(1749, 6)

In [ ]:
df.dtypes

Date       object
Open      float64
High      float64
Low       float64
Close     float64
Volume      int64
dtype: object

### 3. Estructura de los datos

- Utiliza un **único método de pandas para mostrar el número total de filas, columnas, el recuento de valores no nulos y los tipos de datos de cada columna**. Observa atentamente el tipo de dato de la columna 'Date'.

- Muestra el **nombre de las columnas del dataframe**.
- Muestra el **índice del dataframe**.
- Muestra un resumen estadístico de las columnas numéricas del dataframe.

In [ ]:
display(df.describe())
display(df.info())

         Open    High     Low   Close      Volume
count 1749.00 1749.00 1749.00 1749.00     1749.00
mean    12.41   12.56   12.26   12.41  7396379.25
std      2.65    2.66    2.65    2.67  6282541.48
min      5.15    5.36    5.04    5.23   459724.00
25%     10.90   11.04   10.74   10.87  3749189.00
50%     12.82   13.00   12.70   12.84  5445837.00
75%     14.33   14.45   14.18   14.31  8788233.00
max     23.50   24.30   23.40   24.19 61950437.00

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1749 entries, 0 to 1748
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1749 non-null   object
 1   Open    1749 non-null   float64
 2   High    1749 non-null   float64
 3   Low     1749 non-null   float64
 4   Close   1749 non-null   float64
 5   Volume  1749 non-null   int64
dtypes: float64(4), int64(1), object(1)
memory usage: 82.1+ KB

None

In [ ]:

df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)
print(df['Date'].dt.date.dtype) # para mostrar solo la parte de la fecha sin la hora
print(f"Normalizado:\n {pd.to_datetime(df['Date'], dayfirst=True).dt.normalize()}")
display(df.head())
df.dtypes

object
Normalizado:
 0      2019-05-14
1      2019-05-15
2      2019-05-16
3      2019-05-17
4      2019-05-20
          ...
1744   2026-03-11
1745   2026-03-12
1746   2026-03-13
1747   2026-03-16
1748   2026-03-17
Name: Date, Length: 1749, dtype: datetime64[ns]

                 Date  Open  High   Low  Close    Volume
0 2019-05-14 17:36:00 14.21 14.45 14.17  14.42  15796073
1 2019-05-15 17:36:00 14.46 14.53 14.34  14.50   6795939
2 2019-05-16 17:36:00 14.47 14.70 14.42  14.69   7378905
3 2019-05-17 17:36:00 14.69 14.83 14.58  14.79   7442691
4 2019-05-20 17:36:00 14.81 15.04 14.81  14.88   7758119

Date      datetime64[ns]
Open             float64
High             float64
Low              float64
Close            float64
Volume             int64
dtype: object

### 5. Indexación por fecha

- Establece la **columna 'Date' como índice del dataframe**.
- Muestra el **índice del dataframe para confirmar que ahora es de tipo `DatetimeIndex`**.
- Muestra las **primeras filas del dataframe para verificar que la columna 'Date' ya no es una columna normal, sino el índice del dataframe**.
- Muestra el valor de la **cotización de cierre ('Close') para el día 17 de marzo de 2026** utilizando indexación por fecha.

In [ ]:
display(df.set_index('Date', inplace=True))
display(df.index)
print("\nÍndice del dataframe:", df.index)
print("\nPrimeras filas del dataframe:")
display(df.head())

None

DatetimeIndex(['2019-05-14 17:36:00', '2019-05-15 17:36:00',
               '2019-05-16 17:36:00', '2019-05-17 17:36:00',
               '2019-05-20 17:36:00', '2019-05-21 17:36:00',
               '2019-05-22 17:36:00', '2019-05-23 17:36:00',
               '2019-05-24 17:36:00', '2019-05-27 17:36:00',
               ...
               '2026-03-04 17:36:00', '2026-03-05 17:36:00',
               '2026-03-06 17:36:00', '2026-03-09 17:36:00',
               '2026-03-10 17:36:00', '2026-03-11 17:36:00',
               '2026-03-12 17:36:00', '2026-03-13 17:36:00',
               '2026-03-16 17:36:00', '2026-03-17 17:36:00'],
              dtype='datetime64[ns]', name='Date', length=1749, freq=None)

Índice del dataframe: DatetimeIndex(['2019-05-14 17:36:00', '2019-05-15 17:36:00',
               '2019-05-16 17:36:00', '2019-05-17 17:36:00',
               '2019-05-20 17:36:00', '2019-05-21 17:36:00',
               '2019-05-22 17:36:00', '2019-05-23 17:36:00',
               '2019-05-24 17:36:00', '2019-05-27 17:36:00',
               ...
               '2026-03-04 17:36:00', '2026-03-05 17:36:00',
               '2026-03-06 17:36:00', '2026-03-09 17:36:00',
               '2026-03-10 17:36:00', '2026-03-11 17:36:00',
               '2026-03-12 17:36:00', '2026-03-13 17:36:00',
               '2026-03-16 17:36:00', '2026-03-17 17:36:00'],
              dtype='datetime64[ns]', name='Date', length=1749, freq=None)

Primeras filas del dataframe:

                     Open  High   Low  Close    Volume
Date
2019-05-14 17:36:00 14.21 14.45 14.17  14.42  15796073
2019-05-15 17:36:00 14.46 14.53 14.34  14.50   6795939
2019-05-16 17:36:00 14.47 14.70 14.42  14.69   7378905
2019-05-17 17:36:00 14.69 14.83 14.58  14.79   7442691
2019-05-20 17:36:00 14.81 15.04 14.81  14.88   7758119

### 8. Creación de nuevas variables

Crea una **nueva columna llamada 'Rango' que calcule la diferencia entre el precio máximo y el precio mínimo de cada día** (Rango = Maximo - Minimo).

In [ ]:
df['Rango'] = (df['High'] - df['Low']).round(2)
df

                     Open  High   Low  Close    Volume  Rango
Date
2019-05-14 17:36:00 14.21 14.45 14.17  14.42  15796073   0.28
2019-05-15 17:36:00 14.46 14.53 14.34  14.50   6795939   0.19
2019-05-16 17:36:00 14.47 14.70 14.42  14.69   7378905   0.28
2019-05-17 17:36:00 14.69 14.83 14.58  14.79   7442691   0.25
2019-05-20 17:36:00 14.81 15.04 14.81  14.88   7758119   0.23
...                   ...   ...   ...    ...       ...    ...
2026-03-11 17:36:00 20.95 21.78 20.77  21.70   6036241   1.01
2026-03-12 17:36:00 21.79 22.37 21.63  22.27   6941384   0.74
2026-03-13 17:36:00 22.39 23.00 22.35  23.00  10027236   0.65
2026-03-16 17:36:00 23.16 24.30 23.01  23.32   8822412   1.29
2026-03-17 17:36:00 23.50 24.23 23.40  24.19   7910437   0.83

[1749 rows x 6 columns]

### 9. Indexación por fecha
- Muestra la **cotización de cierre ('Cierre') para el mes de marzo de 2025 utilizando indexación por fecha**.
- Muestra la cotización de **cierre para el año 2025 utilizando indexación por fecha**.
- Muestra la cotización de **cierre para el día 17 de marzo de 2026** utilizando indexación por fecha.

In [ ]:
# Todas las filas de marzo de 2026
df_marzo = df.loc['2025-03']
display(df_marzo['Close'])
df_dia = df.loc['2026-03-17','Close']
df_dia

Date
2025-03-03 17:36:00   12.16
2025-03-04 17:36:00   11.85
2025-03-05 17:36:00   11.86
2025-03-06 17:36:00   11.83
2025-03-07 17:36:00   11.78
2025-03-10 17:36:00   11.75
2025-03-11 17:36:00   11.60
2025-03-12 17:36:00   11.58
2025-03-13 17:36:00   11.64
2025-03-14 17:36:00   11.54
2025-03-17 17:36:00   11.87
2025-03-18 17:36:00   12.02
2025-03-19 17:36:00   12.14
2025-03-20 17:36:00   12.07
2025-03-21 17:36:00   12.11
2025-03-24 17:36:00   11.96
2025-03-25 17:36:00   12.15
2025-03-26 17:36:00   12.42
2025-03-27 17:36:00   12.52
2025-03-28 17:36:00   12.46
2025-03-31 17:36:00   12.30
Name: Close, dtype: float64

Date
2026-03-17 17:36:00   24.19
Name: Close, dtype: float64

### 11. Filtrado booleano
¿En qué días el precio de cierre fue superior a 18 euros? Crea una máscara booleana y filtra el dataframe para mostrar solo esos días de alta cotización.

In [ ]:
mascara = df['Close'] > 18
df[mascara]

                     Open  High   Low  Close    Volume  Rango
Date
2026-02-19 17:36:00 17.82 18.20 17.32  18.14   7805787   0.88
2026-02-20 17:36:00 18.27 18.37 17.95  18.30   5774446   0.42
2026-02-23 17:36:00 18.22 18.61 18.08  18.52   3142154   0.53
2026-02-24 17:36:00 18.55 18.75 18.48  18.67   2932305   0.27
2026-02-25 17:36:00 18.66 18.86 18.57  18.84   2437495   0.29
2026-02-26 17:36:00 18.90 18.99 18.56  18.98   3367015   0.43
2026-02-27 17:36:00 18.96 19.20 18.83  19.02   4893072   0.37
2026-03-02 17:36:00 20.00 20.57 19.67  20.04  10521390   0.90
2026-03-03 17:36:00 20.30 20.82 19.95  20.70  13069089   0.87
2026-03-04 17:36:00 20.20 20.57 20.06  20.11   8436930   0.51
2026-03-05 17:36:00 20.71 20.88 20.07  20.22   7698358   0.81
2026-03-06 17:36:00 20.27 20.82 20.19  20.76   8121288   0.63
2026-03-09 17:36:00 20.85 21.11 20.63  20.97   7374520   0.48
2026-03-10 17:36:00 20.19 21.06 19.20  20.75   8143164   1.86
2026-03-11 17:36:00 20.95 21.78 20.77  21.70   6036241   1.01
2026-03-12 17:36:00 21.79 22.37 21.63  22.27   6941384   0.74
2026-03-13 17:36:00 22.39 23.00 22.35  23.00  10027236   0.65
2026-03-16 17:36:00 23.16 24.30 23.01  23.32   8822412   1.29
2026-03-17 17:36:00 23.50 24.23 23.40  24.19   7910437   0.83

### 12. Operaciones entre columnas

Crea una nueva columna llamada 'Cierre_ajustado' que **ajuste el precio de cierre por la inflación acumulada del 4.5%** (es decir, multiplica el precio de cierre por 1.045).

In [ ]:
df['Ajustado'] = (df['Close'] * 1.045).round(2)
df

                     Open  High   Low  Close    Volume  Rango  Ajustado
Date
2019-05-14 17:36:00 14.21 14.45 14.17  14.42  15796073   0.28     15.07
2019-05-15 17:36:00 14.46 14.53 14.34  14.50   6795939   0.19     15.15
2019-05-16 17:36:00 14.47 14.70 14.42  14.69   7378905   0.28     15.35
2019-05-17 17:36:00 14.69 14.83 14.58  14.79   7442691   0.25     15.46
2019-05-20 17:36:00 14.81 15.04 14.81  14.88   7758119   0.23     15.55
...                   ...   ...   ...    ...       ...    ...       ...
2026-03-11 17:36:00 20.95 21.78 20.77  21.70   6036241   1.01     22.68
2026-03-12 17:36:00 21.79 22.37 21.63  22.27   6941384   0.74     23.27
2026-03-13 17:36:00 22.39 23.00 22.35  23.00  10027236   0.65     24.03
2026-03-16 17:36:00 23.16 24.30 23.01  23.32   8822412   1.29     24.37
2026-03-17 17:36:00 23.50 24.23 23.40  24.19   7910437   0.83     25.28

[1749 rows x 7 columns]

### 13. Cálculo de la variación diaria
Crea una nueva columna llamada 'Variacion_diaria' que calcule la variación diaria del precio de cierre respecto al día anterior. La fórmula es: Variacion_diaria = Cierre - Cierre_del_dia_anterior. Utiliza el método `shift()` para acceder al valor del día anterior.

In [ ]:
# df['Valor'].shift(1)

df['VariacionDiaria'] = (df['Close'] - df['Close'].shift(1)).round(2)  
df

,Open,High,Low,Close,Volume,Rango,Ajustado,VariacionDiaria
Date,,,,,,,,
2019-05-14 17:36:00,14.21,14.45,14.17,14.42,15796073,0.28,15.07,NaN
2019-05-15 17:36:00,14.46,14.53,14.34,14.50,6795939,0.19,15.15,0.08
2019-05-16 17:36:00,14.47,14.70,14.42,14.69,7378905,0.28,15.35,0.19
2019-05-17 17:36:00,14.69,14.83,14.58,14.79,7442691,0.25,15.46,0.10
2019-05-20 17:36:00,14.81,15.04,14.81,14.88,7758119,0.23,15.55,0.09
...,...,...,...,...,...,...,...,...
2026-03-11 17:36:00,20.95,21.78,20.77,21.70,6036241,1.01,22.68,0.95
2026-03-12 17:36:00,21.79,22.37,21.63,22.27,6941384,0.74,23.27,0.57
2026-03-13 17:36:00,22.39,23.00,22.35,23.00,10027236,0.65,24.03,0.73
2026-03-16 17:36:00,23.16,24.30,23.01,23.32,8822412,1.29,24.37,0.32
2026-03-17 17:36:00,23.50,24.23,23.40,24.19,7910437,0.83,25.28,0.87

### 14. Cálculo del porcentaje de variación diaria

Crea una nueva columna llamada `Amplitud` que refleje la volatilidad diaria, calculada como la diferencia entre el precio `Maximo` y el precio `Minimo`.

In [ ]:
df['Amplitud'] = (df['High']- df['Low']).round(2)
display(df)

,Open,High,Low,Close,Volume,Rango,Ajustado,VariacionDiaria,Amplitud
Date,,,,,,,,,
2019-05-14 17:36:00,14.21,14.45,14.17,14.42,15796073,0.28,15.07,NaN,0.28
2019-05-15 17:36:00,14.46,14.53,14.34,14.50,6795939,0.19,15.15,0.08,0.19
2019-05-16 17:36:00,14.47,14.70,14.42,14.69,7378905,0.28,15.35,0.19,0.28
2019-05-17 17:36:00,14.69,14.83,14.58,14.79,7442691,0.25,15.46,0.10,0.25
2019-05-20 17:36:00,14.81,15.04,14.81,14.88,7758119,0.23,15.55,0.09,0.23
...,...,...,...,...,...,...,...,...,...
2026-03-11 17:36:00,20.95,21.78,20.77,21.70,6036241,1.01,22.68,0.95,1.01
2026-03-12 17:36:00,21.79,22.37,21.63,22.27,6941384,0.74,23.27,0.57,0.74
2026-03-13 17:36:00,22.39,23.00,22.35,23.00,10027236,0.65,24.03,0.73,0.65
2026-03-16 17:36:00,23.16,24.30,23.01,23.32,8822412,1.29,24.37,0.32,1.29
2026-03-17 17:36:00,23.50,24.23,23.40,24.19,7910437,0.83,25.28,0.87,0.83

### 15. Clasificación categórica (tendencia)

Utiliza `np.where` para crear una columna de texto llamada `Tendencia`. Si la `Variacion` es mayor a 0, el valor será "Alcista". Si es menor o igual a 0, será "Bajista".

In [ ]:
df['Tendencia'] = np.where((df['VariacionDiaria'])> 0,"Alcista","Bajista")
df

,Open,High,Low,Close,Volume,Rango,Ajustado,VariacionDiaria,Amplitud,Tendencia
Date,,,,,,,,,,
2019-05-14 17:36:00,14.21,14.45,14.17,14.42,15796073,0.28,15.07,NaN,0.28,Bajista
2019-05-15 17:36:00,14.46,14.53,14.34,14.50,6795939,0.19,15.15,0.08,0.19,Alcista
2019-05-16 17:36:00,14.47,14.70,14.42,14.69,7378905,0.28,15.35,0.19,0.28,Alcista
2019-05-17 17:36:00,14.69,14.83,14.58,14.79,7442691,0.25,15.46,0.10,0.25,Alcista
2019-05-20 17:36:00,14.81,15.04,14.81,14.88,7758119,0.23,15.55,0.09,0.23,Alcista
...,...,...,...,...,...,...,...,...,...,...
2026-03-11 17:36:00,20.95,21.78,20.77,21.70,6036241,1.01,22.68,0.95,1.01,Alcista
2026-03-12 17:36:00,21.79,22.37,21.63,22.27,6941384,0.74,23.27,0.57,0.74,Alcista
2026-03-13 17:36:00,22.39,23.00,22.35,23.00,10027236,0.65,24.03,0.73,0.65,Alcista
2026-03-16 17:36:00,23.16,24.30,23.01,23.32,8822412,1.29,24.37,0.32,1.29,Alcista
2026-03-17 17:36:00,23.50,24.23,23.40,24.19,7910437,0.83,25.28,0.87,0.83,Alcista

### 16. Eliminación de columnas

El equipo directivo ha decidido que la columna `Amplitud` genera ruido en los informes. Elimínala del dataframe de forma permanente (in-place).

In [ ]:
df = df.drop('Amplitud', axis=1, inplace=True)
df

,Open,High,Low,Close,Volume,Rango,Ajustado,VariacionDiaria,Tendencia
Date,,,,,,,,,
2019-05-14 17:36:00,14.21,14.45,14.17,14.42,15796073,0.28,15.07,NaN,Bajista
2019-05-15 17:36:00,14.46,14.53,14.34,14.50,6795939,0.19,15.15,0.08,Alcista
2019-05-16 17:36:00,14.47,14.70,14.42,14.69,7378905,0.28,15.35,0.19,Alcista
2019-05-17 17:36:00,14.69,14.83,14.58,14.79,7442691,0.25,15.46,0.10,Alcista
2019-05-20 17:36:00,14.81,15.04,14.81,14.88,7758119,0.23,15.55,0.09,Alcista
...,...,...,...,...,...,...,...,...,...
2026-03-11 17:36:00,20.95,21.78,20.77,21.70,6036241,1.01,22.68,0.95,Alcista
2026-03-12 17:36:00,21.79,22.37,21.63,22.27,6941384,0.74,23.27,0.57,Alcista
2026-03-13 17:36:00,22.39,23.00,22.35,23.00,10027236,0.65,24.03,0.73,Alcista
2026-03-16 17:36:00,23.16,24.30,23.01,23.32,8822412,1.29,24.37,0.32,Alcista
2026-03-17 17:36:00,23.50,24.23,23.40,24.19,7910437,0.83,25.28,0.87,Alcista

### 17. Ordenación de valores

Ordena el dataframe por la columna 'Volumen' de forma descendente para identificar los días con las cotizaciones de cierre más altas. Muestra las 5 filas superiores del dataframe ordenado.

In [ ]:
# Ordenar por precio de forma descendente (del más alto)
df_vol = df.sort_values(by=['Volume', 'Close'], ascending=[False, False])
print("\nDataframe ordenado por Volumen:")
print(df_vol.head(5))

Dataframe ordenado por Volumen:
                     Open  High   Low  Close    Volume  Rango  Ajustado  \
Date
2021-07-12 17:36:00  9.88  9.90  9.61   9.75  61950437   0.29     10.19
2022-01-18 17:36:00 11.20 11.29 11.07  11.12  56757167   0.22     11.62
2021-06-28 17:36:00 11.05 11.10 10.65  10.68  55580839   0.45     11.16
2022-01-04 17:36:00 10.70 10.98 10.70  10.89  51878743   0.28     11.38
2020-03-20 17:36:00  6.47  6.64  6.16   6.17  46593106   0.48      6.45

                     VariacionDiaria Tendencia
Date
2021-07-12 17:36:00            -0.10   Bajista
2022-01-18 17:36:00            -0.02   Bajista
2021-06-28 17:36:00            -0.38   Bajista
2022-01-04 17:36:00             0.24   Alcista
2020-03-20 17:36:00             0.14   Alcista

### 18. Agregación múltiple (agg)

Calcula en una sola línea de código el **valor máximo absoluto del precio Maximo, y la media total del Volumen de todo el histórico**.

In [6]:
resultado = df.agg({'High': 'max', 'Volume': 'mean'})
print(resultado)

High          24.30
Volume   7396379.25
dtype: float64

### 19. Re-muestreo temporal (resample)

Agrupa los datos por **meses (frecuencia mensual ‘ME’)** y calcula la media del precio de **Cierre** de cada mes.

Ayuda: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.resample.html

Requiere que el DateFrame sea de tipo `DatetimeIndex`, lo cual ya hemos hecho al establecer la columna 'Date' como índice.

La **regla de frecuencia 'ME' indica que queremos agrupar por meses**, y el método `mean()` calcula la media de cada grupo mensual. El resultado es una serie temporal con la media del precio de cierre para cada mes.

Otras reglas de frecuencia comunes son:
- 'D' para días
- 'B' para días hábiles (business days)
- 'W' para semanas
- 'ME' para fin de mes (Month End)
- 'MS' para inicio de mes (Month Start)
- 'QE' para trimestres (Quarter End)
- 'YE' para años (Year End)
- 'YS' para inicio de año (Year Start)

**Cuando se reduce la frecuencia es obligatorio especificar cómo se agregan los datos dentro de cada grupo**.
**Cuando se aumenta la frecuencia, pandas rellena los nuevos índices con NaN por defecto, pero también se pueden rellenar con otros métodos como forward fill (`ffill`), backward fill (`bfill`) o `.interpolate()`**.

In [16]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)
df_mes = df.resample('QE', on='Date')['Close'].mean()

print(df_mes)

Date
2019-06-30   14.37
2019-09-30   13.63
2019-12-31   14.51
2020-03-31   11.20
2020-06-30    8.34
2020-09-30    6.92
2020-12-31    7.20
2021-03-31    9.59
2021-06-30   10.74
2021-09-30    9.77
2021-12-31   10.76
2022-03-31   11.46
2022-06-30   14.09
2022-09-30   12.50
2022-12-31   13.84
2023-03-31   14.77
2023-06-30   13.37
2023-09-30   14.12
2023-12-31   14.06
2024-03-31   14.06
2024-06-30   14.92
2024-09-30   12.76
2024-12-31   11.66
2025-03-31   11.87
2025-06-30   11.48
2025-09-30   13.73
2025-12-31   15.71
2026-03-31   17.85
Freq: QE-DEC, Name: Close, dtype: float64